### ISSUE TITLE
Síntesis - Calidad de Software

### ISSUE THREAD

**Issue by AndreLuna6** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-AndreLuna6#1]
[Sintesis_LunaGonzalezAndreEmmanuel.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-AndreLuna6/files/9569301/Sintesis_LunaGonzalezAndreEmmanuel.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
